### ISSUE TITLE
国人地图

### ISSUE THREAD

**Issue by allenfred** [supersheep/baidu-map#1]
node后台使用api怎么没有？

**Comment by supersheep** [comment]
这个库就是给node后台使用的。你的疑问是？

**Comment by allenfred** [comment]
谢谢！用了一段时间，挺好，如果你们可以开放一些经纬度计算api:
如：
1.计算两个坐标之间的距离
2.提供一座坐标，筛选距离指定坐标一定距离（1/2/3公里）的坐标
等等之类

**Comment by supersheep** [comment]
这个库的目的只是提供对百度http接口的调用，如果百度有提供，那我这边也可以做相应的封装。
此外的需求可以自己写代码来满足喔。
